local MusicCatalog = {
	{
		id = "balap-karung",
		title = "Bendera",
		artist = "Cokelat",
		soundId = 108881053322600,
		accent = Color3.fromRGB(255, 65, 56),
	},
	{
		id = "soft-keys-1",
		title = "Naykila So",
		artist = "Naykila",
		soundId = 81931065344784,
		accent = Color3.fromRGB(72, 190, 205),
	},
	{
		id = "soft-keys-2",
		title = "Nggak Dulu",
		artist = "Akbar",
		soundId = 109816834964106,
		accent = Color3.fromRGB(72, 190, 205),
	},
	{
		id = "soft-keys-3",
		title = "Kota ini tak sama tanpamu",
		artist = "Unknown Artist",
		soundId = 112858432286509,
		accent = Color3.fromRGB(72, 190, 205),
	},
	{
		id = "pop",
		title = "Everything U Are",
		artist = "Hindia",
		soundId = 121676583384188,
		accent = Color3.fromRGB(0, 194, 255),
	},
	-- {
	-- 	id = "kpop",
	-- 	title = "K-Pop Music",
	-- 	artist = "Unknown Artist",
	-- 	soundId = 130721206402716,
	-- 	accent = Color3.fromRGB(236, 72, 153),
	-- },
	-- {
	-- 	id = "jazz",
	-- 	title = "Jazz Music",
	-- 	artist = "Unknown Artist",
	-- 	soundId = 110267939344127,
	-- 	accent = Color3.fromRGB(245, 171, 38),
	-- },
}

return table.freeze(MusicCatalog)
